import { TimeEntry } from 'src/models/timeEntry';

export function generateDummyTimeEntries(): TimeEntry[] {
  return [
    {
      id: '1',
      date: '2024-11-01',
      startTime: '09:00',
      endTime: '17:00',
      description: 'Weboldal fejlesztés a Klient Kft. számára',
      userName: 'Kovács Gábor',
      tags: ['ügyfél'], 
    },
    {
      id: '2',
      date: '2024-11-02',
      startTime: '10:00',
      endTime: '15:00',
      description: 'Új mobilalkalmazás tervezése a TrendyApp-hoz',
      userName: 'Németh Anna',
      tags: ['projekt', 'ügyfél'], 
    },
    {
      id: '3',
      date: '2024-11-03',
      startTime: '11:00',
      endTime: '18:00',
      description: 'API integrációs kód ellenőrzés',
      userName: 'Szabó László',
      tags: [], 
    },
    {
      id: '4',
      date: '2024-11-04',
      startTime: '08:30',
      endTime: '16:00',
      description: 'Marketing kampány lebonyolítása a MarketMe-nek',
      userName: 'Varga Péter',
      tags: [], 
    },
    {
      id: '5',
      date: '2024-11-05',
      startTime: '09:30',
      endTime: '14:30',
      description: 'UX/UI tervezés az OnlineShop számára',
      userName: 'Kiss Júlia',
      tags: ['projekt'], 
    },
    {
      id: '6',
      date: '2024-11-06',
      startTime: '10:00',
      endTime: '17:30',
      description: 'Weboldal optimalizálás a WebSolutions ügyfél számára',
      userName: 'Tóth András',
      tags: [], 
    },
    {
      id: '7',
      date: '2024-11-07',
      startTime: '09:00',
      endTime: '15:00',
      description: 'Dokumentáció írása a DataAnalyzer projekthez',
      userName: 'Farkas Mária',
      tags: [], 
    },
    {
      id: '8',
      date: '2024-11-08',
      startTime: '10:30',
      endTime: '16:30',
      description: 'Adatbázis fejlesztés a SmartBiz ügyfél számára',
      userName: 'Balogh Zoltán',
      tags: [], 
    },
    {
      id: '9',
      date: '2024-11-09',
      startTime: '08:00',
      endTime: '12:00',
      description: 'SEO optimalizálás az EcoShop számára',
      userName: 'Huszár János',
      tags: [], 
    },
    {
      id: '10',
      date: '2024-11-10',
      startTime: '09:00',
      endTime: '13:00',
      description: 'Online webinárium tartása a Digitális Tanácsadás cégnek',
      userName: 'Kovács Mária',
      tags: [], 
    },
  ];
}
